"""for profiles and their children migrate to many to many

Revision ID: 8c62105e954a
Revises: 5f9134ffd338
Create Date: 2024-04-06 17:04:48.488865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c62105e954a'
down_revision: Union[str, None] = '5f9134ffd338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles_contacts',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('profile_id', 'contact_id')
    )
    op.create_table('profiles_educations',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['educations.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('profile_id', 'contact_id')
    )
    op.create_table('profiles_experiences',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('experience_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('profile_id', 'experience_id')
    )
    op.create_table('profiles_languages',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('profile_id', 'language_id')
    )
    op.create_table('profiles_skills',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('profile_id', 'skill_id')
    )
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_column('contacts', 'profile_id')
    op.drop_constraint(None, 'educations', type_='foreignkey')
    op.drop_column('educations', 'profile_id')
    op.drop_constraint(None, 'experiences', type_='foreignkey')
    op.drop_column('experiences', 'profile_id')
    op.drop_constraint(None, 'languages', type_='foreignkey')
    op.drop_column('languages', 'profile_id')
    op.drop_constraint(None, 'skills', type_='foreignkey')
    op.drop_column('skills', 'profile_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('profile_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'skills', 'profiles', ['profile_id'], ['id'])
    op.add_column('languages', sa.Column('profile_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'languages', 'profiles', ['profile_id'], ['id'])
    op.add_column('experiences', sa.Column('profile_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'experiences', 'profiles', ['profile_id'], ['id'])
    op.add_column('educations', sa.Column('profile_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'educations', 'profiles', ['profile_id'], ['id'])
    op.add_column('contacts', sa.Column('profile_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'contacts', 'profiles', ['profile_id'], ['id'])
    op.drop_table('profiles_skills')
    op.drop_table('profiles_languages')
    op.drop_table('profiles_experiences')
    op.drop_table('profiles_educations')
    op.drop_table('profiles_contacts')
    # ### end Alembic commands ###
